[project]
name = "mcp-server-timetable-restinga-fetcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.1",
    "requests>=2.32.4",
]
